name: Build Crypto Test

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: actions/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Verify Xcode Path (可选调试)
        run: xcode-select -p

      - name: Build Swift Script
        run: swiftc crypto.swift -o CryptoTest

      - name: Run Test
        run: |
          echo "开始运行测试程序..."
          ./CryptoTest
